apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: app
          image: nikpap/payment-service:651
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 40m
              memory: 50Mi
          resources:
            limits:
              memory: 50Mi
              cpu: 10m
            requests:
              memory: 50Mi
              cpu: 10m
          env:
            - name: DB_CONNECTION_STRING
              value: "test_value"
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: prod
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: payment-service
---

